language: node_js
cache:
 - yarn
 - npm
node_js:
 - node
notifications:
 webhooks: https://travis-for-jira-test.toolsplus.app/travis/notifications?token=05be41a1-71d8-3921-afa7-7b765f0d7fa2
 on_success: always
 on_failure: always
 on_start: always
 on_cancel: always
 on_error: always
