language: node_js
cache:
 - yarn
 - npm
node_js:
 - node
notifications:
 webhooks: https://tbinna.ngrok.io/travis/notifications?token=jira:2324r3
 on_success: always
 on_failure: always
 on_start: always
 on_cancel: always
 on_error: always
