os: linux
dist: jammy
arch:
 - arm64
language: node_js
cache:
 - yarn
 - npm
node_js:
 - node
notifications:
 webhooks: https://travis-for-jira-prod.toolsplus.app/travis/notifications?token=d2cb81e0-1484-304b-8e9d-e92e947ca6b1
 on_success: always
 on_failure: always
 on_start: always
 on_cancel: always
 on_error: always
